In [28]:
import numpy as np

#K matrix without exceptions
def K_block(n, k_o):
    A = np.identity(n-1)
    D = A
    k_oArr = k_o * np.ones(n-2)
    B = np.diag(k_oArr, k=1) + np.diag(k_oArr, k=-1)
    C = B
    return np.block([[A,B],[B,A]]) 



In [29]:
print(K_block(4, 0.5))

[[1.  0.  0.  0.  0.5 0. ]
 [0.  1.  0.  0.5 0.  0.5]
 [0.  0.  1.  0.  0.5 0. ]
 [0.  0.5 0.  1.  0.  0. ]
 [0.5 0.  0.5 0.  1.  0. ]
 [0.  0.5 0.  0.  0.  1. ]]


In [3]:
import numpy as np

n=4
k_o = 3

#K matrix without exceptions
def k_block(n, k_o):
    arr_len = n-1
    A = np.identity(arr_len)
    print(A)
    D = A
    diag_len = arr_len-1
    B = k_o * np.diag(np.ones((diag_len)), k=1) + k_o * np.diag(np.ones((diag_len)), k=-1)
    print(B)
    C = B
    print(np.concatenate([A,B]))
    E = np.block([[A,B],[B,A]]) 
    print(E)
    return E

def one_hot_sim(n, i):
    len_arr = n-1
    array_pos = i-1     #(-1 to normalize), p and q refer to normal indices (from 1 to len_arr)
    arr = np.zeros(len_arr)
    if i > 0 and i < n: #if outside, k_o excluded from similarity matrix e.g. AE exception for n=5
        arr[array_pos] = 1 
    return arr

p = 4
q = 2

#columns in k matrix representing exceptions
def k_exp_horiz(n, p, q, k_o):
    A = one_hot_sim(n, p) + one_hot_sim(n, q-1)
    B = one_hot_sim(n, q) + one_hot_sim(n, p-1)
    C = one_hot_sim(n, p-1) + one_hot_sim(n, q)
    D = one_hot_sim(n, q-1) + one_hot_sim(n, p)
    E = k_o * np.block([[A,C],[B,D]])
    return E

def k_iden(k_o):
    arr = k_o * np.identity(2)
    return arr

K = k_block(n, k_o)
E_1 = k_exp_horiz(n, p, q, k_o)
E_2 = K_trans = E_1.transpose()
E_3 = k_iden(k_o)

print('K', K)
print('E_1', E_1)
print('E_2', E_2)
print('E_3', E_3)

def k_block_excep(K, E_1, E_2, E_3):
    W = np.concatenate([K, E_1])
    X = np.concatenate([E_2, E_3])
    Z = np.concatenate([W, X], 1)
    return Z

K = k_block_excep(K, E_1, E_2, E_3)
print('K: \n', K)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 3. 0.]
 [3. 0. 3.]
 [0. 3. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 3. 0.]
 [3. 0. 3.]
 [0. 3. 0.]]
[[1. 0. 0. 0. 3. 0.]
 [0. 1. 0. 3. 0. 3.]
 [0. 0. 1. 0. 3. 0.]
 [0. 3. 0. 1. 0. 0.]
 [3. 0. 3. 0. 1. 0.]
 [0. 3. 0. 0. 0. 1.]]
K [[1. 0. 0. 0. 3. 0.]
 [0. 1. 0. 3. 0. 3.]
 [0. 0. 1. 0. 3. 0.]
 [0. 3. 0. 1. 0. 0.]
 [3. 0. 3. 0. 1. 0.]
 [0. 3. 0. 0. 0. 1.]]
E_1 [[3. 0. 0. 0. 3. 3.]
 [0. 3. 3. 3. 0. 0.]]
E_2 [[3. 0.]
 [0. 3.]
 [0. 3.]
 [0. 3.]
 [3. 0.]
 [3. 0.]]
E_3 [[3. 0.]
 [0. 3.]]
K: 
 [[1. 0. 0. 0. 3. 0. 3. 0.]
 [0. 1. 0. 3. 0. 3. 0. 3.]
 [0. 0. 1. 0. 3. 0. 0. 3.]
 [0. 3. 0. 1. 0. 0. 0. 3.]
 [3. 0. 3. 0. 1. 0. 3. 0.]
 [0. 3. 0. 0. 0. 1. 3. 0.]
 [3. 0. 0. 0. 3. 3. 3. 0.]
 [0. 3. 3. 3. 0. 0. 0. 3.]]


In [5]:
print('K: \n', K)
print(n)

K: 
 [[1. 0. 0. 0. 3. 0. 3. 0.]
 [0. 1. 0. 3. 0. 3. 0. 3.]
 [0. 0. 1. 0. 3. 0. 0. 3.]
 [0. 3. 0. 1. 0. 0. 0. 3.]
 [3. 0. 3. 0. 1. 0. 3. 0.]
 [0. 3. 0. 0. 0. 1. 3. 0.]
 [3. 0. 0. 0. 3. 3. 3. 0.]
 [0. 3. 3. 3. 0. 0. 0. 3.]]
4
