In [47]:
import numpy as np
from scipy.linalg import null_space

# Define matrix K and vector y
K = np.array([
    [1, 0, 0, 0, 0.5, 0, 0.5, 0],
    [0, 1, 0, 0.5, 0, 0.5, 0, 0.5],
    [0, 0, 1, 0, 0.5, 0, 0, 0.5],
    [0, 0.5, 0, 1, 0, 0, 0, 0.5],
    [0.5, 0, 0.5, 0, 1, 0, 0.5, 0],
    [0, 0.5, 0, 0, 0, 1, 0.5, 0],
    [0.5, 0, 0, 0, 0.5, 0.5, 1, 0],
    [0, 0.5, 0.5, 0.5, 0, 0, 0, 1]
])

y = np.array([1, 1, 1, -1, -1, -1, 1, -1])

# Check if K is singular
rank_K = np.linalg.matrix_rank(K)
print(f"Rank of K: {rank_K}")
print(f"Shape of K: {K.shape}")

if rank_K < K.shape[0]:
    print("K is singular")

    # Finding solutions using lstsq
    solution, residuals, rank, s = np.linalg.lstsq(K, y, rcond=None)
    print("Solution from lstsq:", solution)

    # Checking the null space of K
    null_space_K = null_space(K)
    print("Null space of K:", null_space_K)

    # General solution is particular solution


Rank of K: 7
Shape of K: (8, 8)
K is singular
Solution from lstsq: [ 1.50000000e+00  5.00000000e-01  7.30445089e-16 -1.50000000e+00
 -5.00000000e-01  1.39657890e-15 -5.00000000e-01  5.00000000e-01]
Null space of K: [[-0.00000000e+00]
 [ 4.08248290e-01]
 [ 4.08248290e-01]
 [-5.27882848e-16]
 [-4.08248290e-01]
 [-4.08248290e-01]
 [ 4.08248290e-01]
 [-4.08248290e-01]]


In [48]:
import numpy as np
k_o = 0.49

#testing inverse solution
K = np.array([[1,-1,2],[3,2,0],[3,2,0]])
I = np.identity(3)
y = np.array([1,1,-1])
c = 100
W = K-np.dot((1/c),I)
a = np.linalg.solve(W, y)
print(a)

A = np.array([[4,7],[2,6]])
I_2 = np.identity(2)
print(np.linalg.solve(A, I_2))

#K matrix without exceptions
def K_block(n, k_o):
    A = np.identity(n-1)
    D = A
    k_oArr = k_o * np.ones(n-2)
    B = np.diag(k_oArr, k=1) + np.diag(k_oArr, k=-1)
    C = B
    return np.block([[A,B],[B,A]])    
    
#def tridiag_exception()

[  771.92931353 -1163.21002039  -963.21002039]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [49]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
import numpy as np
A = np.array([[1,1]])
C = 3 * A
B = np.array([[2]])
D = 2 * B
np.block([[A,B],[C,D]])

array([[1, 1, 2],
       [3, 3, 4]])

In [51]:
import numpy as np

# Define sub-blocks as 2D arrays
A = np.array([[1, 1]])  # 1x2 array
B = np.array([[2]])     # 1x1 array

# Element-wise multiplication to scale the arrays
C = 3 * A  # Multiplies each element in A by 3, resulting in a 1x2 array
D = 2 * B  # Multiplies each element in B by 2, resulting in a 1x1 array

# Combine these sub-blocks into a block matrix using np.block
block_matrix = np.block([[A, B],
                         [C, D]])

print(block_matrix)


[[1 1 2]
 [3 3 4]]


In [52]:
import numpy as np
n=4
k_o = 0.5
diag_len = n-1
B = k_o * np.diag(np.ones((diag_len)), k=1) + k_o * np.diag(np.ones((diag_len)), k=-1)
print(B)

[[0.  0.5 0.  0. ]
 [0.5 0.  0.5 0. ]
 [0.  0.5 0.  0.5]
 [0.  0.  0.5 0. ]]


In [53]:
import numpy as np

n=4
k_o = 0.49

#K matrix without exceptions
def k_block(n, k_o, return_k):
    arr_len = n-1
    A = np.identity(arr_len)
    D = A
    diag_len = arr_len-1
    B = k_o * np.diag(np.ones((diag_len)), k=1) + k_o * np.diag(np.ones((diag_len)), k=-1)
    C = B
    E = np.block([[A,B],[B,A]]) 
    if return_k == False:
        return B
    else:
        return E

def one_hot_sim(n, i):
    len_arr = n-1
    array_pos = i-1     #(-1 to normalize), p and q refer to normal indices (from 1 to len_arr)
    arr = np.zeros(len_arr)
    if i > 0 and i < n: #if outside, k_o excluded from similarity matrix e.g. AE exception for n=5
        arr[array_pos] = 1 
    return arr

n = 7
p = 5
q = 3

#columns in k matrix representing exceptions
def k_exp_horiz(n, p, q, k_o):
    A = one_hot_sim(n, p) + one_hot_sim(n, q-1)
    B = one_hot_sim(n, q) + one_hot_sim(n, p-1)
    C = one_hot_sim(n, p-1) + one_hot_sim(n, q)
    D = one_hot_sim(n, q-1) + one_hot_sim(n, p)
    E = k_o * np.block([[A,C],[B,D]])

    print('A', A)
    print('B', B)
    print('C', C)
    print('D', D)
    return E

K = k_block(n, k_o, True)
E_1 = k_exp_horiz(n, p, q, k_o)
E_2 = K_trans = E_1.transpose()
E_3 = np.identity(2) #2 since there's only 2 columns for exceptions

print('K', K)
print('E_1', E_1)
print('E_2', E_2)
print('E_3', E_3)

def k_block_excep(K, E_1, E_2, E_3):
    W = np.concatenate([K, E_1])
    print('W', W)
    X = np.concatenate([E_2, E_3])
    print('X', X)
    Z = np.concatenate([W, X], 1)
    print('Z', Z)
    return Z

K = k_block_excep(K, E_1, E_2, E_3)
print(K)





A [0. 1. 0. 0. 1. 0.]
B [0. 0. 1. 1. 0. 0.]
C [0. 0. 1. 1. 0. 0.]
D [0. 1. 0. 0. 1. 0.]
K [[1.   0.   0.   0.   0.   0.   0.   0.49 0.   0.   0.   0.  ]
 [0.   1.   0.   0.   0.   0.   0.49 0.   0.49 0.   0.   0.  ]
 [0.   0.   1.   0.   0.   0.   0.   0.49 0.   0.49 0.   0.  ]
 [0.   0.   0.   1.   0.   0.   0.   0.   0.49 0.   0.49 0.  ]
 [0.   0.   0.   0.   1.   0.   0.   0.   0.   0.49 0.   0.49]
 [0.   0.   0.   0.   0.   1.   0.   0.   0.   0.   0.49 0.  ]
 [0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.   0.   0.  ]
 [0.49 0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.   0.  ]
 [0.   0.49 0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.  ]
 [0.   0.   0.49 0.   0.49 0.   0.   0.   0.   1.   0.   0.  ]
 [0.   0.   0.   0.49 0.   0.49 0.   0.   0.   0.   1.   0.  ]
 [0.   0.   0.   0.   0.49 0.   0.   0.   0.   0.   0.   1.  ]]
E_1 [[0.   0.49 0.   0.   0.49 0.   0.   0.   0.49 0.49 0.   0.  ]
 [0.   0.   0.49 0.49 0.   0.   0.   0.49 0.   0.   0.49 0.  ]]
E_2 [[0.   0.  ]
 [0.4

In [54]:
np.linalg.det(K)

0.00030601018911752964

In [55]:
len(K)

14

In [56]:
print(K)
I = np.identity(n-1)

def create_y(n):
    A = np.ones(n-1)
    B = A * -1
    C = np.array([1, -1])
    D = np.concatenate([A, B, C])
    return D
y = create_y(n)
print('y', y)

c = 100
K_ridge = K + ((1/c) * np.identity(len(K)))
print(K_ridge)
a = np.linalg.solve(K_ridge, y)
print(a)

[[1.   0.   0.   0.   0.   0.   0.   0.49 0.   0.   0.   0.   0.   0.  ]
 [0.   1.   0.   0.   0.   0.   0.49 0.   0.49 0.   0.   0.   0.49 0.  ]
 [0.   0.   1.   0.   0.   0.   0.   0.49 0.   0.49 0.   0.   0.   0.49]
 [0.   0.   0.   1.   0.   0.   0.   0.   0.49 0.   0.49 0.   0.   0.49]
 [0.   0.   0.   0.   1.   0.   0.   0.   0.   0.49 0.   0.49 0.49 0.  ]
 [0.   0.   0.   0.   0.   1.   0.   0.   0.   0.   0.49 0.   0.   0.  ]
 [0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.49 0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.   0.   0.   0.49]
 [0.   0.49 0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.   0.49 0.  ]
 [0.   0.   0.49 0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.49 0.  ]
 [0.   0.   0.   0.49 0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.49]
 [0.   0.   0.   0.   0.49 0.   0.   0.   0.   0.   0.   1.   0.   0.  ]
 [0.   0.49 0.   0.   0.49 0.   0.   0.   0.49 0.49 0.   0.   1.   0.  ]
 [0.   0.   0.49 0.49 0.   0.   0.   0.49 0.   0.  

In [57]:
print(K)
I = np.identity(n-1)

def create_y(n):
    A = np.ones(n-1)
    B = A * -1
    C = np.array([1, -1])
    D = np.concatenate([A, B, C])
    return D
y = create_y(n)
print('y', y)
a = np.linalg.solve(K, y)
print(a)

[[1.   0.   0.   0.   0.   0.   0.   0.49 0.   0.   0.   0.   0.   0.  ]
 [0.   1.   0.   0.   0.   0.   0.49 0.   0.49 0.   0.   0.   0.49 0.  ]
 [0.   0.   1.   0.   0.   0.   0.   0.49 0.   0.49 0.   0.   0.   0.49]
 [0.   0.   0.   1.   0.   0.   0.   0.   0.49 0.   0.49 0.   0.   0.49]
 [0.   0.   0.   0.   1.   0.   0.   0.   0.   0.49 0.   0.49 0.49 0.  ]
 [0.   0.   0.   0.   0.   1.   0.   0.   0.   0.   0.49 0.   0.   0.  ]
 [0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.49 0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.   0.   0.   0.49]
 [0.   0.49 0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.   0.49 0.  ]
 [0.   0.   0.49 0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.49 0.  ]
 [0.   0.   0.   0.49 0.   0.49 0.   0.   0.   0.   1.   0.   0.   0.49]
 [0.   0.   0.   0.   0.49 0.   0.   0.   0.   0.   0.   1.   0.   0.  ]
 [0.   0.49 0.   0.   0.49 0.   0.   0.   0.49 0.49 0.   0.   1.   0.  ]
 [0.   0.   0.49 0.49 0.   0.   0.   0.49 0.   0.  

In [58]:
#inverse solution for exceptions
K_inv = np.linalg.inv(K_ridge)
print(K_inv)
a = np.dot(K_inv, y)
print(a)


[[ 1.67552719 -0.18608041  0.57420425 -0.29128587  0.19881342  0.11423979
   0.09027663 -1.41282135  0.17346887 -0.43315304 -0.23547384 -0.09645404
   0.11980799  0.66241053]
 [-0.18608041  2.91214198 -0.35755829  0.89282565  0.48536445  0.19881342
  -1.41282135  0.38355349 -1.18356386  0.60040556 -0.40979909 -0.23547384
  -1.36537682 -0.24695115]
 [ 0.57420425 -0.35755829  7.35246347  4.54079212  0.89282565 -0.29128587
   0.17346887 -1.18356386 -4.47292058 -6.44362067  0.60040556 -0.43315304
   5.0364596  -5.4870769 ]
 [-0.29128587  0.89282565  4.54079212  7.35246347 -0.35755829  0.57420425
  -0.43315304  0.60040556 -6.44362067 -4.47292058 -1.18356386  0.17346887
   5.0364596  -5.4870769 ]
 [ 0.19881342  0.48536445  0.89282565 -0.35755829  2.91214198 -0.18608041
  -0.23547384 -0.40979909  0.60040556 -1.18356386  0.38355349 -1.41282135
  -1.36537682 -0.24695115]
 [ 0.11423979  0.19881342 -0.29128587  0.57420425 -0.18608041  1.67552719
  -0.09645404 -0.23547384 -0.43315304  0.17346887 -

In [59]:
#dual coefficients
print(a)
print(n)


[  3.45697259   5.08478024  34.99436154  34.99436154   5.08478024
   3.45697259  -3.45697259  -5.08478024 -34.99436154 -34.99436154
  -5.08478024  -3.45697259  30.01127691 -30.01127691]
7


In [60]:
n = 7
p = 5
q = 3

# Create a dictionary with keys generated using the index and values from the array
num_coeff = n-1
b = {i: a[i-1] for i in range(1, num_coeff + 1)}
b_bar = {i: a[i-1+n-1] for i in range(1, num_coeff + 1)}
c = {1: a[2 * num_coeff]}
c_bar = {1: a[2 * num_coeff + 1]}
print(b)
print(b_bar)
print(c[1])
print(c_bar[1])

{1: 3.4569725896446757, 2: 5.084780235798208, 3: 34.99436154369407, 4: 34.994361543694076, 5: 5.084780235798208, 6: 3.456972589644675}
{1: -3.456972589644675, 2: -5.084780235798209, 3: -34.994361543694076, 4: -34.994361543694076, 5: -5.084780235798208, 6: -3.456972589644673}
30.011276912611834
-30.011276912611827


In [61]:
#f(j,k)

def e_i(i,n):
    e = np.zeros(n-1)
    if i >= 1 and i < n:
        i = i-1
        e[i] = 1

    return e

print(e_i(4, 4))

A = k_block(4, 1, False)
B = np.linalg.inv(np.identity(n-1) - (A*k_o))
b_til = B * np.identity(n-1)


K_mult = np.ones(n-1) - (c[1]*k_o*(e_i(p, 4) + e_i(q-1, 4) - e_i(p-1, 4) - e_i(q, 4)))
b_analytical = np.dot(B, K_mult)

c_analytical = 1 - (k_o * (b_bar[q-1] - b_bar[p-1] - b_bar[q]))
print(b_analytical)
print(b)
print(c)
print(c_analytical)

print(n, p, q)

[0. 0. 0.]


ValueError: operands could not be broadcast together with shapes (6,6) (3,3) 

In [ ]:
n = 7
p = 5
q = 3

c_reg = 1e10

lamb = np.arccosh((1 + (1/c_reg))/(1-k_o))

def sinh(x):
    return np.sinh(x)

def tanh(x):
    return np.tanh(x)

def cosh(x):
    return np.cosh(x)

num = 1 + (
sinh( (((n+1)/2 - q) * lamb)) - sinh( ((n+1)/2 - p) * lamb)  / 
( sinh( (((n+1)/2) * lamb)) - sinh( ((n-1)/2) * lamb))
)

denom = 1 - 2*k_o - \
    4*k_o * (tanh(lamb/2) / sinh(lamb * n)) * sinh((q-p)/2 * lamb) * \
    cosh((q-1/2)*lamb) * sinh((n - (p+q)/2 + 1/2)*lamb) + cosh((n - p + 1/2)*lamb) * sinh(((p+q)/2 - 1/2)*lamb)

c_exp = num/denom
print(c_exp)

0.004600039816361394


In [ ]:
print(K[2*(n-1),:])
print(a)
print(np.dot(K, a))

print(len(K_inv))
print(np.dot(K_inv[2*(n-1),:], y))
print(np.dot(K[2*(n-1),:], a))
print(K[2*(n-1),:])


[0.49 0.   0.   0.   0.49 0.49 1.   0.  ]
[  1.44955547  33.80685479  33.33333333  -1.44955547 -33.80685479
 -33.33333333  32.85981188 -32.85981188]
[ 0.98550445  0.66193145  0.66666667 -0.98550445 -0.66193145 -0.66666667
  0.67140188 -0.67140188]
8
32.85981187991236
0.6714018812008788
[0.49 0.   0.   0.   0.49 0.49 1.   0.  ]


In [ ]:
c[1]

32.85981187991236

In [ ]:
print(A)

[[0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]
