In [1]:
import numpy as np
from scipy.linalg import null_space

# Define matrix K and vector y
K = np.array([
    [1, 0, 0, 0, 0.5, 0, 0.5, 0],
    [0, 1, 0, 0.5, 0, 0.5, 0, 0.5],
    [0, 0, 1, 0, 0.5, 0, 0, 0.5],
    [0, 0.5, 0, 1, 0, 0, 0, 0.5],
    [0.5, 0, 0.5, 0, 1, 0, 0.5, 0],
    [0, 0.5, 0, 0, 0, 1, 0.5, 0],
    [0.5, 0, 0, 0, 0.5, 0.5, 1, 0],
    [0, 0.5, 0.5, 0.5, 0, 0, 0, 1]
])

y = np.array([1, 1, 1, -1, -1, -1, 1, -1])

# Check if K is singular
rank_K = np.linalg.matrix_rank(K)
print(f"Rank of K: {rank_K}")
print(f"Shape of K: {K.shape}")

if rank_K < K.shape[0]:
    print("K is singular")

    # Finding solutions using lstsq
    solution, residuals, rank, s = np.linalg.lstsq(K, y, rcond=None)
    print("Solution from lstsq:", solution)

    # Checking the null space of K
    null_space_K = null_space(K)
    print("Null space of K:", null_space_K)

    # General solution is particular solution


Rank of K: 7
Shape of K: (8, 8)
K is singular
Solution from lstsq: [ 1.50000000e+00  5.00000000e-01  7.30445089e-16 -1.50000000e+00
 -5.00000000e-01  1.39657890e-15 -5.00000000e-01  5.00000000e-01]
Null space of K: [[-0.00000000e+00]
 [ 4.08248290e-01]
 [ 4.08248290e-01]
 [-5.27882848e-16]
 [-4.08248290e-01]
 [-4.08248290e-01]
 [ 4.08248290e-01]
 [-4.08248290e-01]]


In [2]:
import numpy as np
k_o = 0.49

#testing inverse solution
K = np.array([[1,-1,2],[3,2,0],[3,2,0]])
I = np.identity(3)
y = np.array([1,1,-1])
c = 100
W = K-np.dot((1/c),I)
a = np.linalg.solve(W, y)
print(a)

A = np.array([[4,7],[2,6]])
I_2 = np.identity(2)
print(np.linalg.solve(A, I_2))

#K matrix without exceptions
def K_block(n, k_o):
    A = np.identity(n-1)
    D = A
    k_oArr = k_o * np.ones(n-2)
    B = np.diag(k_oArr, k=1) + np.diag(k_oArr, k=-1)
    C = B
    return np.block([[A,B],[B,A]])    
    
#def tridiag_exception()

[  771.92931353 -1163.21002039  -963.21002039]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [3]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
import numpy as np
A = np.array([[1,1]])
C = 3 * A
B = np.array([[2]])
D = 2 * B
np.block([[A,B],[C,D]])

array([[1, 1, 2],
       [3, 3, 4]])

In [5]:
import numpy as np

# Define sub-blocks as 2D arrays
A = np.array([[1, 1]])  # 1x2 array
B = np.array([[2]])     # 1x1 array

# Element-wise multiplication to scale the arrays
C = 3 * A  # Multiplies each element in A by 3, resulting in a 1x2 array
D = 2 * B  # Multiplies each element in B by 2, resulting in a 1x1 array

# Combine these sub-blocks into a block matrix using np.block
block_matrix = np.block([[A, B],
                         [C, D]])

print(block_matrix)


[[1 1 2]
 [3 3 4]]


In [6]:
import numpy as np
n=4
k_o = 0.5
diag_len = n-1
B = k_o * np.diag(np.ones((diag_len)), k=1) + k_o * np.diag(np.ones((diag_len)), k=-1)
print(B)

[[0.  0.5 0.  0. ]
 [0.5 0.  0.5 0. ]
 [0.  0.5 0.  0.5]
 [0.  0.  0.5 0. ]]


In [7]:
import numpy as np

n=4
k_o = 0.49

#K matrix without exceptions
def k_block(n, k_o, return_k):
    arr_len = n-1
    A = np.identity(arr_len)
    D = A
    diag_len = arr_len-1
    B = k_o * np.diag(np.ones((diag_len)), k=1) + k_o * np.diag(np.ones((diag_len)), k=-1)
    C = B
    E = np.block([[A,B],[B,A]]) 
    if return_k == False:
        return B
    else:
        return E

def one_hot_sim(n, i):
    len_arr = n-1
    array_pos = i-1     #(-1 to normalize), p and q refer to normal indices (from 1 to len_arr)
    arr = np.zeros(len_arr)
    if i > 0 and i < n: #if outside, k_o excluded from similarity matrix e.g. AE exception for n=5
        arr[array_pos] = 1 
    return arr

p = 4
q = 2

#columns in k matrix representing exceptions
def k_exp_horiz(n, p, q, k_o):
    A = one_hot_sim(n, p) + one_hot_sim(n, q-1)
    B = one_hot_sim(n, q) + one_hot_sim(n, p-1)
    C = one_hot_sim(n, p-1) + one_hot_sim(n, q)
    D = one_hot_sim(n, q-1) + one_hot_sim(n, p)
    E = k_o * np.block([[A,C],[B,D]])

    print('A', A)
    print('B', B)
    print('C', C)
    print('D', D)
    return E

K = k_block(n, k_o, True)
E_1 = k_exp_horiz(n, p, q, k_o)
E_2 = K_trans = E_1.transpose()
E_3 = np.identity(2) #2 since there's only 2 columns for exceptions

print('K', K)
print('E_1', E_1)
print('E_2', E_2)
print('E_3', E_3)

def k_block_excep(K, E_1, E_2, E_3):
    W = np.concatenate([K, E_1])
    print('W', W)
    X = np.concatenate([E_2, E_3])
    print('X', X)
    Z = np.concatenate([W, X], 1)
    print('Z', Z)
    return Z

K = k_block_excep(K, E_1, E_2, E_3)
print(K)





A [1. 0. 0.]
B [0. 1. 1.]
C [0. 1. 1.]
D [1. 0. 0.]
K [[1.   0.   0.   0.   0.49 0.  ]
 [0.   1.   0.   0.49 0.   0.49]
 [0.   0.   1.   0.   0.49 0.  ]
 [0.   0.49 0.   1.   0.   0.  ]
 [0.49 0.   0.49 0.   1.   0.  ]
 [0.   0.49 0.   0.   0.   1.  ]]
E_1 [[0.49 0.   0.   0.   0.49 0.49]
 [0.   0.49 0.49 0.49 0.   0.  ]]
E_2 [[0.49 0.  ]
 [0.   0.49]
 [0.   0.49]
 [0.   0.49]
 [0.49 0.  ]
 [0.49 0.  ]]
E_3 [[1. 0.]
 [0. 1.]]
W [[1.   0.   0.   0.   0.49 0.  ]
 [0.   1.   0.   0.49 0.   0.49]
 [0.   0.   1.   0.   0.49 0.  ]
 [0.   0.49 0.   1.   0.   0.  ]
 [0.49 0.   0.49 0.   1.   0.  ]
 [0.   0.49 0.   0.   0.   1.  ]
 [0.49 0.   0.   0.   0.49 0.49]
 [0.   0.49 0.49 0.49 0.   0.  ]]
X [[0.49 0.  ]
 [0.   0.49]
 [0.   0.49]
 [0.   0.49]
 [0.49 0.  ]
 [0.49 0.  ]
 [1.   0.  ]
 [0.   1.  ]]
Z [[1.   0.   0.   0.   0.49 0.   0.49 0.  ]
 [0.   1.   0.   0.49 0.   0.49 0.   0.49]
 [0.   0.   1.   0.   0.49 0.   0.   0.49]
 [0.   0.49 0.   1.   0.   0.   0.   0.49]
 [0.49 0.   0.49 0.   

In [8]:
np.linalg.det(K)

0.008127739635840014

In [9]:
len(K)

8

In [10]:
print(K)
I = np.identity(n-1)

def create_y(n):
    A = np.ones(n-1)
    B = A * -1
    C = np.array([1, -1])
    D = np.concatenate([A, B, C])
    return D
y = create_y(n)
print('y', y)

c = 100
K_ridge = K + ((1/c) * np.identity(len(K)))
print(K_ridge)
a = np.linalg.solve(K_ridge, y)
print(a)

[[1.   0.   0.   0.   0.49 0.   0.49 0.  ]
 [0.   1.   0.   0.49 0.   0.49 0.   0.49]
 [0.   0.   1.   0.   0.49 0.   0.   0.49]
 [0.   0.49 0.   1.   0.   0.   0.   0.49]
 [0.49 0.   0.49 0.   1.   0.   0.49 0.  ]
 [0.   0.49 0.   0.   0.   1.   0.49 0.  ]
 [0.49 0.   0.   0.   0.49 0.49 1.   0.  ]
 [0.   0.49 0.49 0.49 0.   0.   0.   1.  ]]
y [ 1.  1.  1. -1. -1. -1.  1. -1.]
[[1.01 0.   0.   0.   0.49 0.   0.49 0.  ]
 [0.   1.01 0.   0.49 0.   0.49 0.   0.49]
 [0.   0.   1.01 0.   0.49 0.   0.   0.49]
 [0.   0.49 0.   1.01 0.   0.   0.   0.49]
 [0.49 0.   0.49 0.   1.01 0.   0.49 0.  ]
 [0.   0.49 0.   0.   0.   1.01 0.49 0.  ]
 [0.49 0.   0.   0.   0.49 0.49 1.01 0.  ]
 [0.   0.49 0.49 0.49 0.   0.   0.   1.01]]
[  1.44955547  33.80685479  33.33333333  -1.44955547 -33.80685479
 -33.33333333  32.85981188 -32.85981188]


In [11]:
print(K)
I = np.identity(n-1)

def create_y(n):
    A = np.ones(n-1)
    B = A * -1
    C = np.array([1, -1])
    D = np.concatenate([A, B, C])
    return D
y = create_y(n)
print('y', y)
a = np.linalg.solve(K, y)
print(a)

[[1.   0.   0.   0.   0.49 0.   0.49 0.  ]
 [0.   1.   0.   0.49 0.   0.49 0.   0.49]
 [0.   0.   1.   0.   0.49 0.   0.   0.49]
 [0.   0.49 0.   1.   0.   0.   0.   0.49]
 [0.49 0.   0.49 0.   1.   0.   0.49 0.  ]
 [0.   0.49 0.   0.   0.   1.   0.49 0.  ]
 [0.49 0.   0.   0.   0.49 0.49 1.   0.  ]
 [0.   0.49 0.49 0.49 0.   0.   0.   1.  ]]
y [ 1.  1.  1. -1. -1. -1.  1. -1.]
[  1.47553971  50.4852446   50.          -1.47553971 -50.4852446
 -50.          49.5147554  -49.5147554 ]


In [12]:
#inverse solution for exceptions
K_inv = np.linalg.inv(K_ridge)
print(K_inv)
a = np.dot(K_inv, y)
print(a)


[[ 1.64846549 -0.2049991   0.42863825  0.19891002 -0.67852055  0.42863825
  -0.67852055 -0.2049991 ]
 [-0.2049991   6.79117193  5.00268462 -0.67852055 -4.9190673  -5.88620427
   5.34161646 -5.39258875]
 [ 0.42863825  5.00268462  6.70146553  0.42863825 -5.88620427 -4.85409002
   5.00268462 -5.88620427]
 [ 0.19891002 -0.67852055  0.42863825  1.64846549 -0.2049991   0.42863825
  -0.2049991  -0.67852055]
 [-0.67852055 -4.9190673  -5.88620427 -0.2049991   6.79117193  5.00268462
  -5.39258875  5.34161646]
 [ 0.42863825 -5.88620427 -4.85409002  0.42863825  5.00268462  6.70146553
  -5.88620427  5.00268462]
 [-0.67852055  5.34161646  5.00268462 -0.2049991  -5.39258875 -5.88620427
   6.79117193 -4.9190673 ]
 [-0.2049991  -5.39258875 -5.88620427 -0.67852055  5.34161646  5.00268462
  -4.9190673   6.79117193]]
[  1.44955547  33.80685479  33.33333333  -1.44955547 -33.80685479
 -33.33333333  32.85981188 -32.85981188]


In [13]:
#dual coefficients
print(a)
print(n)


[  1.44955547  33.80685479  33.33333333  -1.44955547 -33.80685479
 -33.33333333  32.85981188 -32.85981188]
4


In [14]:
n=4
# Create a dictionary with keys generated using the index and values from the array
num_coeff = n-1
b = {i: a[i-1] for i in range(1, num_coeff + 1)}
b_bar = {i: a[i-1+n-1] for i in range(1, num_coeff + 1)}
c = {1: a[2 * num_coeff]}
c_bar = {1: a[2 * num_coeff + 1]}
print(b)
print(b_bar)
print(c[1])
print(c_bar[1])

{1: 1.4495554696559723, 2: 33.80685478675426, 3: 33.333333333333314}
{1: -1.4495554696559716, 2: -33.80685478675426, 3: -33.33333333333331}
32.85981187991236
-32.85981187991236


In [15]:
p
b

{1: 1.4495554696559723, 2: 33.80685478675426, 3: 33.333333333333314}

In [16]:
#f(j,k)

def e_i(i,n):
    e = np.zeros(n-1)
    if i >= 1 and i < n:
        i = i-1
        e[i] = 1

    return e

print(e_i(4, 4))

A = k_block(4, 1, False)
B = np.linalg.inv(np.identity(n-1) - (A*k_o))
b_til = B * np.identity(n-1)


K_mult = np.ones(n-1) - (c[1]*k_o*(e_i(p, 4) + e_i(q-1, 4) - e_i(p-1, 4) - e_i(q, 4)))
b_analytical = np.dot(B, K_mult)

c_analytical = 1 - (k_o * (b_bar[q-1] - b_bar[p-1] - b_bar[q]))
print(b_analytical)
print(b)
print(c)
print(c_analytical)

print(np.dot(K_inv[2*(n-1),:], b))



    
sol(1,1,1,1,0.5)

[0. 0. 0.]
[ 1.94340328 34.7851247  34.14601893]
{1: 1.4495554696559723, 2: 33.80685478675426, 3: 33.333333333333314}
{1: 32.85981187991236}
-31.188409998711478


TypeError: unsupported operand type(s) for *: 'float' and 'dict'

In [ ]:
print(K[2*(n-1),:])
print(a)
print(np.dot(K, a))

print(len(K_inv))
print(np.dot(K_inv[2*(n-1),:], y))
print(np.dot(K[2*(n-1),:], a))
print(K[2*(n-1),:])


[3. 0. 0. 0. 3. 3. 3. 0.]
[-0.29268293 -0.41463415 -0.19512195  0.29268293  0.41463415  0.19512195
  0.01626016 -0.01626016]
[ 1.  1.  1. -1. -1. -1.  1. -1.]
8
0.01626016260162602
1.0
[3. 0. 0. 0. 3. 3. 3. 0.]


In [ ]:
c[1]

0.01626016260162602

In [ ]:
print(A)

[[0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]
