In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from Ranking_exp import Ranking_exp

#check final formula
# uses rank_mult_exp_analytical
    # uses "previous" form
    # rank = rank_til(j) + c_analytical_form() * alpha_prime * (D_ij_analytical_sol(j, q) - D_ij_analytical_sol(j, p) + delta(j,q) - delta(j,p))

sim = Ranking_exp(n=8, k_o=0.4, k_s=1, k_d=0, p=4, q=2, c_var=0) 
ranks = sim.calc_rank()   

    

# Print Values
# x_vals = np.arange(1, 6)
# plt.plot(x_vals, ranks, label=f'n = 5')



1: -0.7283417916787769
2: -0.09251268751816469
3: -0.19656151490084783
4: -0.39889109973395276
5: -0.10704464664982503
6: 0.13127948310939247
7: 0.43524335442330475
8: 0.95682890294887


In [22]:
print(ranks)

[ 0.67283731  0.00925596  0.10537558  0.25418298 -0.2249911  -0.81666073]


In [23]:
print(ranks[4])
print(ranks[1])
rank_test_analytical_2_5 = ranks[4] - ranks[1]
print(rank_test_analytical_2_5)

# implies the rank formula is opposite??
# something is off because these formulas can't be opposite.....

-0.22499110003559986
0.00925596297614839
-0.23424706301174825


In [24]:
#check actual values
#rank_test is f(1,3) = rank(3) - rank(1)
sim = Ranking_exp(n=5, k_o=0.4, k_s=1, k_d=0, p=4, q=2, c_var=0) 
ranktest_actual_2_5 = sim.f_j_k(2,5)
print(ranktest_actual_2_5)




0.5217391304347826


In [28]:
#check actual values
#rank_test is f(1,3) = rank(3) - rank(1)
sim = Ranking_exp(n=5, k_o=0.4, k_s=1, k_d=0, p=4, q=2, c_var=0) 
ranks = sim.calc_rank_analytic()
print(ranks)

[ 0.60869565 -0.08695652  0.          0.08695652 -0.60869565]


Progress:

- [x] Check to see if the ranking formula is correct? (Why does f(j,k) = r_k - r_j?)
  - Look at the paper to check this


In [26]:
#testing
# This shows something weird but the ordering shows a monotonic ranking system
# This also shows that the formula is doing the inverse.  
sim = Ranking_exp(n=5, k_o=0.4, k_s=1, k_d=0, p=4, q=2, c_var=0)
ranks = sim.calc_rank_test() 
print(ranks)

1: -0.6086956521739131
2: 0.08695652173913047
3: 0.0
4: -0.08695652173913047
5: 0.6086956521739131
[ 0.60869565 -0.08695652 -0.          0.08695652 -0.60869565]
